services:
  - type: web
    name: telegram-garant-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: 5979001063  # ВАШ ID сюда!
